### ISSUE TITLE
Ruby 2.1 : invalid base64 when reading account_key.json

### ISSUE THREAD

**Issue by sdaubert** [sdaubert/letscert#3]
letscert 0.4.2 on ruby 2.1 : when reading a previously generated account_key.json, ruby raises:
```
/usr/lib/ruby/2.1.0/base64.rb:73:in `unpack': invalid base64 (ArgumentError)
	from /usr/lib/ruby/2.1.0/base64.rb:73:in `strict_decode64'
	from /usr/lib/ruby/2.1.0/base64.rb:89:in `urlsafe_decode64'
	from /var/lib/gems/2.1.0/gems/letscert-0.4.2/lib/letscert/io_plugins/jwk_io_plugin_mixin.rb:23:in `urlsafe_decode64'
```

This error does not appear on ruby 2.3.

**Comment by sdaubert** [comment]
In Ruby < 2.3, `Base64.urlsafe_decode64` uses `Base64.strict_decode64`, whiich raises when argument is not padded.
But RFC4648 specifies in §3.2 that padding is not mandatory for specifications referring to it explicitly states that base64 encoding MUST NOT use padding. And this is the case for [JWK](http://openid.net/specs/draft-jones-json-web-key-03.html#anchor8).

Ruby 2.3 fixes this bug but this is not done in previous versions.
